# Generated by Django 6.0 on 2025-12-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('team', models.CharField(max_length=120)),
                ('meet', models.CharField(max_length=120)),
                ('time', models.CharField(max_length=120)),
                ('event', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
                ('nqt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Swimmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('team', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
                ('races', models.ManyToManyField(to='Races.races')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=120)),
                ('swimmers', models.ManyToManyField(to='Races.swimmers')),
            ],
        ),
    ]
