# Generated by Django 6.0 on 2025-12-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Races', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='swimmers',
        ),
        migrations.DeleteModel(
            name='Swimmers',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
