# Generated by Django 6.0 on 2025-12-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Races', '0002_remove_teams_swimmers_delete_swimmers_delete_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='slug',
            field=models.SlugField(default=0, max_length=120, unique=False),
            preserve_default=False,
        ),
    ]
