# Generated by Django 6.0 on 2025-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Races', '0003_races_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
    ]
