# Generated by Django 6.0 on 2025-12-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Races', '0004_alter_races_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='races',
            old_name='slug',
            new_name='meet_slug',
        ),
        migrations.AddField(
            model_name='races',
            name='name_slug',
            field=models.SlugField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='races',
            name='team_slug',
            field=models.SlugField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
