# Generated by Django 6.0 on 2025-12-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Races', '0005_rename_slug_races_meet_slug_races_name_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='place',
            field=models.IntegerField(),
        ),
    ]
