# Generated by Django 6.0 on 2026-01-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Races', '0006_alter_races_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='division',
            field=models.CharField(default='', max_length=120),
        ),
    ]
